// Mock data for negotiations. Realistic flavor for IBEW Local 1430 + NYRA CCTV.

const DEMO_NEGOTIATIONS = [
  {
    id: "ibew-1430",
    name: "IBEW Local 1430",
    client: "International Brotherhood of Electrical Workers, Local 1430",
    employer: "ConEd Westchester Operations",
    industry: "Utilities / Electrical",
    members: 412,
    status: "active",
    phase: "Mid-table exchange",
    cbaExpires: "2026-06-30",
    nextSession: "2026-06-02T10:00:00",
    sessionLocation: "Local 1430 Hall, White Plains",
    daysToExpiry: 35,
    teamLead: "You",
    bargainingTeam: [
      { name: "You", role: "Lead Negotiator", initials: "YO", color: "#1F4A47" },
      { name: "M. Rivera", role: "Business Mgr", initials: "MR", color: "#B47A1A" },
      { name: "D. Foster", role: "E-Board Rep", initials: "DF", color: "#2C5AA0" },
      { name: "K. Nguyen", role: "Steward", initials: "KN", color: "#7A3F8F" },
      { name: "P. O'Brien", role: "Analyst", initials: "PO", color: "#2F7D4F" },
    ],
    counterparts: [
      { name: "H. Calderon", role: "VP Labor Relations", initials: "HC", color: "#8B919A" },
      { name: "R. Mendelsohn", role: "Outside Counsel", initials: "RM", color: "#8B919A" },
    ],
    summary: "Three-year CBA renewal covering 412 inside wiremen and apprentices. Economic package is the live wire — wages, health contribution, retiree medical. Non-economic mostly cleaned up in Session 4.",
    sessions: [
      { n: 1, date: "2026-04-08", topic: "Ground rules, openers exchanged", outcome: "ground-rules-signed" },
      { n: 2, date: "2026-04-15", topic: "Non-economic openers", outcome: "exchanged" },
      { n: 3, date: "2026-04-22", topic: "Hours of work, overtime, premium pay", outcome: "partial-ta" },
      { n: 4, date: "2026-04-29", topic: "Grievance procedure, discipline, seniority", outcome: "ta-reached" },
      { n: 5, date: "2026-05-06", topic: "Health & welfare, pension", outcome: "exchanged" },
      { n: 6, date: "2026-05-13", topic: "Wages, classifications", outcome: "exchanged" },
      { n: 7, date: "2026-05-20", topic: "Counters — economics package", outcome: "active" },
      { n: 8, date: "2026-06-02", topic: "Caucus + economic counter", outcome: "scheduled" },
    ],
    articles: [
      { id: "art-2",  num: "2",  title: "Recognition & Bargaining Unit", status: "ta", topic: "non-econ", priority: "low",
        proposals: 2, lastMove: "Union", lastDate: "2026-04-15",
        summary: "Carryover from prior CBA. Clarified inclusion of new substation tech classification." },
      { id: "art-5",  num: "5",  title: "Union Security & Dues Checkoff", status: "ta", topic: "non-econ", priority: "low",
        proposals: 2, lastMove: "Employer", lastDate: "2026-04-22",
        summary: "Standard language. TA'd Session 4." },
      { id: "art-7",  num: "7",  title: "Hours of Work & Overtime", status: "ta", topic: "non-econ", priority: "med",
        proposals: 4, lastMove: "Joint", lastDate: "2026-04-22",
        summary: "Compromise on weekend OT trigger — 8hr daily preserved, weekend storm-call rate increased." },
      { id: "art-9",  num: "9",  title: "Grievance & Arbitration", status: "ta", topic: "non-econ", priority: "med",
        proposals: 3, lastMove: "Joint", lastDate: "2026-04-29",
        summary: "Step 2 timeline tightened to 15 days. Arbitrator panel refreshed." },
      { id: "art-11", num: "11", title: "Seniority & Layoff", status: "ta", topic: "non-econ", priority: "med",
        proposals: 3, lastMove: "Union", lastDate: "2026-04-29",
        summary: "Bumping rights preserved; cross-classification rules clarified for substation work." },
      { id: "art-14", num: "14", title: "Discipline & Discharge", status: "ta", topic: "non-econ", priority: "med",
        proposals: 2, lastMove: "Joint", lastDate: "2026-04-29",
        summary: "Just-cause language unchanged. Removed disciplinary records purge at 18 months." },
      { id: "art-18", num: "18", title: "Wages & Classifications", status: "open", topic: "econ", priority: "high",
        proposals: 5, lastMove: "Employer", lastDate: "2026-05-20",
        summary: "Active. Union opened 18% over 3yr; employer at 8.5% over 4yr. Gap remains on wage progression for apprentices." },
      { id: "art-19", num: "19", title: "Health & Welfare Contribution", status: "open", topic: "econ", priority: "high",
        proposals: 4, lastMove: "Employer", lastDate: "2026-05-13",
        summary: "Employer proposes shifting 3% premium cost to members; Union proposes cap on member share at 1%." },
      { id: "art-20", num: "20", title: "Pension & 401(k) Match", status: "open", topic: "econ", priority: "high",
        proposals: 3, lastMove: "Union", lastDate: "2026-05-13",
        summary: "Union seeks defined-benefit hourly contribution increase of $1.85; Employer counters $0.60." },
      { id: "art-21", num: "21", title: "Retiree Medical", status: "open", topic: "econ", priority: "high",
        proposals: 2, lastMove: "Employer", lastDate: "2026-05-06",
        summary: "Employer proposes closing retiree medical to new hires after CBA execution. Union opposes." },
      { id: "art-23", num: "23", title: "Apprenticeship & Training", status: "open", topic: "non-econ", priority: "med",
        proposals: 2, lastMove: "Union", lastDate: "2026-04-15",
        summary: "Union seeks training fund increase tied to wage scale. Employer reviewing." },
      { id: "art-27", num: "27", title: "Subcontracting", status: "tentative", topic: "non-econ", priority: "high",
        proposals: 4, lastMove: "Employer", lastDate: "2026-05-20",
        summary: "Close to TA — notice + first-refusal language on subcontracting in. Union wants 30-day, employer 14-day." },
      { id: "art-31", num: "31", title: "Duration & Wage Reopener", status: "open", topic: "econ", priority: "low",
        proposals: 1, lastMove: "Union", lastDate: "2026-04-15",
        summary: "Tied to package. Will resolve last." },
    ],
    folders: standardFolderTree(),
    chat: [
      { id: 1, author: "M. Rivera", initials: "MR", color: "#B47A1A", time: "Today, 9:42 AM",
        text: "Heads up — Calderon's office called. They want to add a sidebar on Art. 21 before tomorrow's main session." },
      { id: 2, author: "You",       initials: "YO", color: "#1F4A47", time: "Today, 9:48 AM",
        text: "Take the sidebar. Don't move on retiree medical without me. Push them to put their best number on H&W in the main." },
      { id: 3, author: "P. O'Brien", initials: "PO", color: "#2F7D4F", time: "Today, 10:11 AM",
        text: "Refreshed the cost model with their latest H&W counter — see /Proposal Review/Cost Models/HW-counter-v3.xlsx. Total package now $4.2M over 3yr.",
        attachment: { type: "xlsx", name: "HW-counter-v3.xlsx" } },
      { id: 4, author: "K. Nguyen", initials: "KN", color: "#7A3F8F", time: "Today, 10:34 AM",
        text: "Got word from the floor — members are firm on retiree medical. Will not ratify if it closes to new hires." },
      { id: 5, author: "D. Foster", initials: "DF", color: "#2C5AA0", time: "Today, 11:02 AM",
        text: "Agree with Kim. We've already taken movement on H&W premium share. This is the line." },
    ],
    activity: [
      { id: 1, time: "2h ago",  text: "Employer uploaded counter on Article 18 — Wages",  who: "H. Calderon", kind: "proposal-recv" },
      { id: 2, time: "5h ago",  text: "AI updated Article 18 history thread (5 moves)",   who: "System",       kind: "ai" },
      { id: 3, time: "Yesterday", text: "Tentative agreement reached on Article 27 — Subcontracting", who: "Joint", kind: "ta" },
      { id: 4, time: "Yesterday", text: "Caucus notes from Session 6 added to record",     who: "K. Nguyen",   kind: "note" },
      { id: 5, time: "2 days ago", text: "Cost model v3 published",                        who: "P. O'Brien",  kind: "doc" },
      { id: 6, time: "3 days ago", text: "Session 6 scheduled for May 13",                 who: "M. Rivera",   kind: "calendar" },
    ],
  },
  {
    id: "nyra-cctv",
    name: "NYRA CCTV Operators",
    client: "Communications Workers Local 1102 — NYRA Surveillance Unit",
    employer: "New York Racing Association",
    industry: "Gaming / Racing",
    members: 47,
    status: "active",
    phase: "Openers exchanged",
    cbaExpires: "2026-08-31",
    nextSession: "2026-05-28T13:00:00",
    sessionLocation: "Belmont Park — Admin Bldg, Conf Room B",
    daysToExpiry: 97,
    teamLead: "You",
    bargainingTeam: [
      { name: "You",         role: "Lead Negotiator", initials: "YO", color: "#1F4A47" },
      { name: "A. Whitman",  role: "Local Pres",      initials: "AW", color: "#B47A1A" },
      { name: "J. Park",     role: "Chief Steward",   initials: "JP", color: "#2C5AA0" },
    ],
    counterparts: [
      { name: "S. Bellini",  role: "Director of HR",  initials: "SB", color: "#8B919A" },
    ],
    summary: "47-member surveillance/CCTV operator unit. First negotiation since unit certified in 2023. Focus: shift differential, equipment training stipend, fixed-schedule protections.",
    sessions: [
      { n: 1, date: "2026-05-14", topic: "Ground rules, intros, openers", outcome: "ground-rules-signed" },
      { n: 2, date: "2026-05-21", topic: "Non-economic openers exchange", outcome: "exchanged" },
      { n: 3, date: "2026-05-28", topic: "Hours, scheduling, premium pay", outcome: "scheduled" },
    ],
    articles: [
      { id: "n-1", num: "1", title: "Recognition", status: "ta", topic: "non-econ", priority: "low",
        proposals: 1, lastMove: "Joint", lastDate: "2026-05-14",
        summary: "Standard recognition clause carried from card-check agreement." },
      { id: "n-3", num: "3", title: "Hours & Scheduling", status: "open", topic: "non-econ", priority: "high",
        proposals: 2, lastMove: "Union", lastDate: "2026-05-21",
        summary: "Union proposes 28-day posted schedule with limits on involuntary shift changes. Employer reviewing." },
      { id: "n-4", num: "4", title: "Shift Differential", status: "open", topic: "econ", priority: "high",
        proposals: 1, lastMove: "Union", lastDate: "2026-05-21",
        summary: "Union opener: $2.25/hr swing, $3.50/hr graveyard. No employer counter yet." },
      { id: "n-6", num: "6", title: "Equipment & Training Stipend", status: "open", topic: "econ", priority: "med",
        proposals: 1, lastMove: "Union", lastDate: "2026-05-21",
        summary: "Annual $400 stipend for cert renewal on new GIB-12 monitoring rig. Novel ask — no template." },
      { id: "n-9", num: "9", title: "Grievance Procedure", status: "open", topic: "non-econ", priority: "med",
        proposals: 1, lastMove: "Union", lastDate: "2026-05-21",
        summary: "Three-step + arbitration. Standard template." },
      { id: "n-12", num: "12", title: "Wages", status: "open", topic: "econ", priority: "high",
        proposals: 0, lastMove: "—", lastDate: "—",
        summary: "Not yet exchanged. Scheduled for Session 5." },
    ],
    folders: standardFolderTree(),
    chat: [
      { id: 1, author: "A. Whitman", initials: "AW", color: "#B47A1A", time: "Yesterday, 4:18 PM",
        text: "Bellini's team isn't going to move on the GIB-12 stipend without comp data from peer tracks. Can we pull Aqueduct + Saratoga?" },
      { id: 2, author: "You",        initials: "YO", color: "#1F4A47", time: "Yesterday, 4:42 PM",
        text: "Pulling it. Saratoga has a $475 cert reimbursement; Aqueduct has $325. Our $400 is defensible mid-range." },
    ],
    activity: [
      { id: 1, time: "Yesterday", text: "Session 3 confirmed — May 28, 1pm", who: "S. Bellini", kind: "calendar" },
      { id: 2, time: "2 days ago", text: "Article 3 counter received from Employer", who: "S. Bellini", kind: "proposal-recv" },
      { id: 3, time: "5 days ago", text: "Openers exchanged at Session 2", who: "Joint", kind: "doc" },
    ],
  },
];

const ARCHIVE_NEGOTIATIONS = [
  { id: "saratoga-2024", name: "Saratoga Grooms Council", client: "Backstretch Workers United", employer: "NYRA Saratoga", status: "ratified", cbaExpires: "2027-12-31", ratifiedDate: "2024-09-12", members: 188 },
  { id: "ibew-1430-2023", name: "IBEW 1430 — 2023 Reopener", client: "IBEW Local 1430", employer: "ConEd Westchester", status: "ratified", cbaExpires: "2026-06-30", ratifiedDate: "2023-07-08", members: 398 },
];

// Standard folder structure auto-generated for every negotiation
function standardFolderTree() {
  return [
    {
      id: "our-proposals", name: "01 — Our Proposals", icon: "folder-us", auto: true,
      meta: "Outgoing — drafts & finals",
      children: [
        { id: "f1-1", name: "Initial Openers — 2026.docx", kind: "docx", size: "84 KB", modified: "Apr 8" },
        { id: "f1-2", name: "Wage Opener v1 — 18 pct.docx", kind: "docx", size: "62 KB", modified: "May 6" },
        { id: "f1-3", name: "H&W Counter v2.docx", kind: "docx", size: "71 KB", modified: "May 13" },
        { id: "f1-4", name: "Subcontracting Language Final.docx", kind: "docx", size: "44 KB", modified: "May 20" },
      ],
    },
    {
      id: "their-proposals", name: "02 — Their Proposals", icon: "folder-them", auto: true,
      meta: "Incoming — employer/counterpart",
      children: [
        { id: "f2-1", name: "Employer Openers — Non-Econ.pdf", kind: "pdf", size: "1.2 MB", modified: "Apr 15" },
        { id: "f2-2", name: "Employer Wage Counter 8.5pct.docx", kind: "docx", size: "58 KB", modified: "May 20" },
        { id: "f2-3", name: "Retiree Medical Closure Proposal.docx", kind: "docx", size: "39 KB", modified: "May 6" },
      ],
    },
    {
      id: "by-article", name: "03 — By Article (AI-tracked)", icon: "folder-articles", auto: true,
      meta: "One folder per item — AI updates history",
      pinned: true,
      children: [
        { id: "a-18", name: "Article 18 — Wages",            kind: "thread", proposals: 5, status: "open" },
        { id: "a-19", name: "Article 19 — Health & Welfare", kind: "thread", proposals: 4, status: "open" },
        { id: "a-20", name: "Article 20 — Pension",          kind: "thread", proposals: 3, status: "open" },
        { id: "a-21", name: "Article 21 — Retiree Medical",  kind: "thread", proposals: 2, status: "open" },
        { id: "a-27", name: "Article 27 — Subcontracting",   kind: "thread", proposals: 4, status: "tentative" },
        { id: "a-7",  name: "Article 7 — Hours / OT",        kind: "thread", proposals: 4, status: "ta" },
      ],
    },
    {
      id: "caucus", name: "04 — Caucus Room", icon: "folder-caucus", auto: true,
      meta: "Private to your side — Teams/Zoom recordings + notes",
      children: [
        { id: "c-1", name: "Caucus — May 13 (Pre-session).m4a",    kind: "audio", size: "48 MB", modified: "May 13" },
        { id: "c-2", name: "Caucus — May 13 — AI Notes.docx",      kind: "docx", size: "22 KB", modified: "May 13" },
        { id: "c-3", name: "Caucus — May 20 (Mid-session).m4a",    kind: "audio", size: "32 MB", modified: "May 20" },
        { id: "c-4", name: "Caucus — May 20 — AI Notes.docx",      kind: "docx", size: "18 KB", modified: "May 20" },
        { id: "c-5", name: "Strategy Memo — Economic Package.docx", kind: "docx", size: "94 KB", modified: "May 22" },
      ],
    },
    {
      id: "review", name: "05 — Proposal Review & Drafting", icon: "folder-review", auto: true,
      meta: "Working drafts before they go out",
      children: [
        { id: "r-1", name: "Wage Counter v4 — DRAFT.docx",        kind: "docx", size: "66 KB", modified: "Today" },
        { id: "r-2", name: "Retiree Medical Carve-out — DRAFT.docx", kind: "docx", size: "48 KB", modified: "Today" },
        { id: "r-3", name: "Cost Models", kind: "folder",
          children: [
            { id: "r-3-1", name: "Package Model v3.xlsx", kind: "xlsx", size: "412 KB", modified: "May 22" },
            { id: "r-3-2", name: "HW-counter-v3.xlsx",    kind: "xlsx", size: "204 KB", modified: "Today" },
          ],
        },
      ],
    },
    {
      id: "tentative", name: "06 — Tentatively Agreed (TA)", icon: "folder-ta", auto: true,
      meta: "Locked language — moves to Final on ratification",
      children: [
        { id: "t-1", name: "TA — Article 2 Recognition.docx",          kind: "docx", modified: "Apr 15", taDate: "Apr 15" },
        { id: "t-2", name: "TA — Article 5 Union Security.docx",       kind: "docx", modified: "Apr 22", taDate: "Apr 22" },
        { id: "t-3", name: "TA — Article 7 Hours & OT.docx",           kind: "docx", modified: "Apr 22", taDate: "Apr 22" },
        { id: "t-4", name: "TA — Article 9 Grievance.docx",            kind: "docx", modified: "Apr 29", taDate: "Apr 29" },
        { id: "t-5", name: "TA — Article 11 Seniority.docx",           kind: "docx", modified: "Apr 29", taDate: "Apr 29" },
        { id: "t-6", name: "TA — Article 14 Discipline.docx",          kind: "docx", modified: "Apr 29", taDate: "Apr 29" },
      ],
    },
    {
      id: "final", name: "07 — Final Agreement", icon: "folder-final", auto: true,
      meta: "Sealed CBA — populated on ratification",
      children: [
        { id: "fa-placeholder", name: "Awaiting ratification…", kind: "placeholder" },
      ],
    },
    {
      id: "research", name: "08 — Research & Reference", icon: "folder-research", auto: true,
      meta: "Comp data, past CBAs, BLS, peer locals",
      children: [
        { id: "rs-1", name: "Prior CBA 2023-2026.pdf", kind: "pdf", size: "3.4 MB", modified: "Apr 1" },
        { id: "rs-2", name: "BLS Wage Comp — Electrical NY.xlsx", kind: "xlsx", size: "180 KB", modified: "Apr 3" },
        { id: "rs-3", name: "Peer Locals — H&W Survey.pdf", kind: "pdf", size: "2.1 MB", modified: "Apr 5" },
      ],
    },
    {
      id: "correspondence", name: "09 — Correspondence", icon: "folder-mail", auto: true,
      meta: "Email threads — synced from Outlook",
      children: [
        { id: "co-1", name: "Calderon ↔ You — Session Logistics", kind: "email-thread", count: 14, modified: "Today" },
        { id: "co-2", name: "Rivera ↔ Membership — Bargaining Updates", kind: "email-thread", count: 8, modified: "Yesterday" },
      ],
    },
  ];
}

// Proposal history for Article 18 — the deep-dive example
const ARTICLE_18_HISTORY = [
  {
    id: "p1", side: "union", round: 1, date: "2026-05-06", session: 5,
    title: "Union Opener — Wages",
    headline: "18% over 3 years",
    detail: "Year 1: 7%  ·  Year 2: 6%  ·  Year 3: 5%. Apprentice scale tied to JIW at 50/60/70/80/90%. New substation tech classification slotted at JIW + $1.85.",
    author: "M. Rivera",
    docName: "Wage Opener v1 — 18 pct.docx",
    annual: 1450000,
  },
  {
    id: "p2", side: "employer", round: 1, date: "2026-05-13", session: 6,
    title: "Employer Response",
    headline: "6% over 4 years",
    detail: "Year 1: 1.5%  ·  Year 2: 1.5%  ·  Year 3: 1.5%  ·  Year 4: 1.5%. Apprentice scale unchanged. Substation tech at JIW + $0.50.",
    author: "H. Calderon",
    docName: "Employer Wage Response 6pct-4yr.docx",
    annual: 380000,
    aiNote: "Employer added a fourth year — duration shift, not just rate. Treat as structural, not just economic.",
  },
  {
    id: "p3", side: "union", round: 2, date: "2026-05-13", session: 6,
    title: "Union Counter",
    headline: "14% over 3 years",
    detail: "Year 1: 6%  ·  Year 2: 5%  ·  Year 3: 3%. Apprentice scale held. Substation tech at JIW + $1.40 (movement of $0.45).",
    author: "M. Rivera",
    docName: "Wage Counter v2 — 14 pct.docx",
    annual: 1140000,
  },
  {
    id: "p4", side: "employer", round: 2, date: "2026-05-20", session: 7,
    title: "Employer Counter",
    headline: "8.5% over 4 years",
    detail: "Year 1: 2.5%  ·  Year 2: 2%  ·  Year 3: 2%  ·  Year 4: 2%. Substation tech at JIW + $0.85. Now offering signing bonus of $1,200/member.",
    author: "H. Calderon",
    docName: "Employer Wage Counter 8.5pct.docx",
    annual: 540000,
    aiNote: "Signing bonus is new variable — $494K one-time. Employer is buying duration. Recommend modeling 3yr vs 4yr total package.",
  },
  {
    id: "p5", side: "union", round: 3, date: null, session: null,
    title: "Union Counter (drafting)",
    headline: "12% over 3 years + $750 bonus",
    detail: "Working draft — Year 1: 5.5%  ·  Year 2: 4%  ·  Year 3: 2.5%. Holding 3-year duration. Signing bonus accepted at $750. Substation tech at JIW + $1.20.",
    author: "P. O'Brien",
    docName: "Wage Counter v4 — DRAFT.docx",
    annual: 980000,
    isDraft: true,
  },
];

Object.assign(window, { DEMO_NEGOTIATIONS, ARCHIVE_NEGOTIATIONS, ARTICLE_18_HISTORY });
